name: 'hw1-checker'

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: run script
        run: |
              chmod +x "${GITHUB_WORKSPACE}/hw1/hw1script.sh"
              ./${GITHUB_WORKSPACE}/hw1/hw1script.sh